server:
  address: ":8000"
  openapiPath: "/api.json"
#  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true
  path: "./log/"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"

database:
  default:
    host: "192.168.9.27"
    port: "1521"
    user: "quote"
    pass: "quote"
    name: "ORCL"
    type: "oracle"
  newrmb:
    host: "10.18.7.23"
    port: "1521"
    user: "NEWRMBTRADE"
    pass: "NEWRMBTRADE"
    name: "ORCL"
    type: "oracle"
  FITRADE:
    host: "192.168.87.235"
    port: "1521"
    user: "FITRADINGSYSTEMV21"
    pass: "FITRADINGSYSTEMV21"
    name: "FITRADE"
    type: "oracle"



rabbitmq:
  address: "amqp://ocr:ocr@192.168.9.27:5672/"
  xbondHq: "XBOND_HQ"
  marketmakerHq: "MM_HQ"
  Client2Server: "Client2Server"
  Server2Client: "Server2Client"

clordid:
  sc: "QRapi01150"
  test: "QRdhzqtrd0"

caculate:
  address: "http://192.168.87.235:8899/applyCalculateResult"
#  address: "http://10.28.7.48:8899/applyCalculateResult"

quoteparams:
  partyID101_803_266: "101929"
  partyID101_803_2: "lijianbo"