// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CBMARKETQUOTE is the golang structure of table CBMARKETQUOTE for DAO operations like Where/Data.
type CBMARKETQUOTE struct {
	g.Meta                 `orm:"table:CBMARKETQUOTE, do:true"`
	ID                     interface{} //
	BUSSINESSCODE          interface{} //
	REMARK                 interface{} //
	USERID                 interface{} //
	BUYACCRUEDINTERESTAMT  interface{} //
	BUYCLEARINGMETHOD      interface{} //
	BUYDELIVERYTYPE        interface{} //
	BUYORDERQTY            interface{} //
	BUYPRICE               interface{} //
	BUYSECURITYID          interface{} //
	BUYSETTLCURRFXRATE     interface{} //
	BUYSETTLCURRENCY       interface{} //
	BUYSETTLTYPE           interface{} //
	BUYSTRIKEYEILDYILED    interface{} //
	BUYYTMYILED            interface{} //
	CHANNEL                interface{} //
	CHANNELTYPE            interface{} //
	CLORDID                interface{} //
	CONTINGENCYINDICATOR   interface{} //
	DATASOURCESTRING       interface{} //
	DATECONFIRMED          interface{} //
	MARKETINDICATOR        interface{} //
	MARKETSCOPE            interface{} //
	MAXFLOOR               interface{} //
	PARTYID101             interface{} //
	PARTYID206             interface{} //
	PARTYSUBID101803101    interface{} //
	PARTYSUBID101803125    interface{} //
	PARTYSUBID101803135    interface{} //
	PARTYSUBID1018032      interface{} //
	PARTYSUBID101803266    interface{} //
	PARTYSUBID101803267    interface{} //
	PARTYSUBID10180329     interface{} //
	PARTYSUBID206803135    interface{} //
	QUOTEID                interface{} //
	QUOTESTATUS            interface{} //
	QUOTETRANSTYPE         interface{} //
	QUOTETYPE              interface{} //
	ROUTINGTYPE            interface{} //
	SECURITYDESC           interface{} //
	SECURITYID             interface{} //
	SECURITYTYPEID         interface{} //
	SELLACCRUEDINTERESTAMT interface{} //
	SELLCLEARINGMETHOD     interface{} //
	SELLDELIVERYTYPE       interface{} //
	SELLORDERQTY           interface{} //
	SELLPRICE              interface{} //
	SELLSECURITYID         interface{} //
	SELLSETTLCURRFXRATE    interface{} //
	SELLSETTLCURRENCY      interface{} //
	SELLSETTLTYPE          interface{} //
	SELLSTRIKEYEILDYILED   interface{} //
	SELLYTMYILED           interface{} //
	STATUS                 interface{} //
	SYMBOL                 interface{} //
	TERMTOMATURITYSTRING   interface{} //
	TRANSACTTIME           interface{} //
	USERREFERENCE1         interface{} //
	USERREFERENCE2         interface{} //
	USERREFERENCE3         interface{} //
	USERREFERENCE4         interface{} //
	USERREFERENCE5         interface{} //
	USERREFERENCE6         interface{} //
	VALIDUNTILTIME         interface{} //
	QUOTESTATUSDESC        interface{} //
	BUYLASTQTY             interface{} //
	SELLLASTQTY            interface{} //
}
