// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CBMARKETQUOTESW is the golang structure of table CBMARKETQUOTESW for DAO operations like Where/Data.
type CBMARKETQUOTESW struct {
	g.Meta           `orm:"table:CBMARKETQUOTESW, do:true"`
	ID               interface{} //
	MDBOOKTYPE       interface{} //
	MDENTRYDATE      interface{} //
	MDENTRYPX        interface{} //
	MDENTRYSIZE      interface{} //
	MDENTRYTIME      interface{} //
	MDENTRYTYPE      interface{} //
	MDPRICELEVEL     interface{} //
	MDQUOTETYPE      interface{} //
	MDSUBBOOKTYPE    interface{} //
	CLEARINGMETHOD   interface{} //
	DELIVERYTYPE     interface{} //
	LASTPX           interface{} //
	MARKETDEPTH      interface{} //
	MARKETINDICATOR  interface{} //
	MATURITYYIELD    interface{} //
	MDID             interface{} //
	MDREQID          interface{} //
	PARTYID101       interface{} //
	PARTYID1018032   interface{} //
	PARTYID101803266 interface{} //
	QUOTEENTRYID     interface{} //
	SECURITYID       interface{} //
	SECURITYTYPE     interface{} //
	SETTLCURRFXRATE  interface{} //
	SETTLCURRENCY    interface{} //
	SETTLDATE        interface{} //
	SETTLTYPE        interface{} //
	SYMBOL           interface{} //
	INSERTTIME       *gtime.Time //
}
