package model

type CBMARKETQUOTE struct {
	ID                     int     `json:"iD"                     ` //
	BUSSINESSCODE          string  `json:"bUSSINESSCODE"          ` //
	REMARK                 string  `json:"rEMARK"                 ` //
	USERID                 int     `json:"uSERID"                 ` //
	BUYACCRUEDINTERESTAMT  string  `json:"bUYACCRUEDINTERESTAMT"  ` //
	BUYCLEARINGMETHOD      string  `json:"bUYCLEARINGMETHOD"      ` //
	BUYDELIVERYTYPE        string  `json:"bUYDELIVERYTYPE"        ` //
	BUYORDERQTY            int32   `json:"bUYORDERQTY"            ` //
	BUYPRICE               float64 `json:"bUYPRICE"               ` //
	BUYSECURITYID          string  `json:"bUYSECURITYID"          ` //
	BUYSETTLCURRFXRATE     string  `json:"bUYSETTLCURRFXRATE"     ` //
	BUYSETTLCURRENCY       string  `json:"bUYSETTLCURRENCY"       ` //
	BUYSETTLTYPE           string  `json:"bUYSETTLTYPE"           ` //
	BUYSTRIKEYEILDYILED    string  `json:"bUYSTRIKEYEILDYILED"    ` //
	BUYYTMYILED            float64 `json:"bUYYTMYILED"            ` //
	CHANNEL                string  `json:"cHANNEL"                ` //
	CHANNELTYPE            string  `json:"cHANNELTYPE"            ` //
	CLORDID                string  `json:"cLORDID"                ` //
	CONTINGENCYINDICATOR   string  `json:"cONTINGENCYINDICATOR"   ` //
	DATASOURCESTRING       string  `json:"dATASOURCESTRING"       ` //
	DATECONFIRMED          string  `json:"dATECONFIRMED"          ` //
	MARKETINDICATOR        string  `json:"mARKETINDICATOR"        ` //
	MARKETSCOPE            string  `json:"mARKETSCOPE"            ` //
	MAXFLOOR               int32   `json:"mAXFLOOR"               ` //
	PARTYID101             string  `json:"pARTYID101"             ` //
	PARTYID206             string  `json:"pARTYID206"             ` //
	PARTYSUBID101803101    string  `json:"pARTYSUBID101803101"    ` //
	PARTYSUBID101803125    string  `json:"pARTYSUBID101803125"    ` //
	PARTYSUBID101803135    string  `json:"pARTYSUBID101803135"    ` //
	PARTYSUBID1018032      string  `json:"pARTYSUBID1018032"      ` //
	PARTYSUBID101803266    string  `json:"pARTYSUBID101803266"    ` //
	PARTYSUBID101803267    string  `json:"pARTYSUBID101803267"    ` //
	PARTYSUBID10180329     string  `json:"pARTYSUBID10180329"     ` //
	PARTYSUBID206803135    string  `json:"pARTYSUBID206803135"    ` //
	QUOTEID                string  `json:"qUOTEID"                ` //
	QUOTESTATUS            string  `json:"qUOTESTATUS"            ` //
	QUOTETRANSTYPE         string  `json:"qUOTETRANSTYPE"         ` //
	QUOTETYPE              string  `json:"qUOTETYPE"              ` //
	ROUTINGTYPE            string  `json:"rOUTINGTYPE"            ` //
	SECURITYDESC           string  `json:"sECURITYDESC"           ` //
	SECURITYID             string  `json:"sECURITYID"             ` //
	SECURITYTYPEID         string  `json:"sECURITYTYPEID"         ` //
	SELLACCRUEDINTERESTAMT string  `json:"sELLACCRUEDINTERESTAMT" ` //
	SELLCLEARINGMETHOD     string  `json:"sELLCLEARINGMETHOD"     ` //
	SELLDELIVERYTYPE       string  `json:"sELLDELIVERYTYPE"       ` //
	SELLORDERQTY           int32   `json:"sELLORDERQTY"           ` //
	SELLPRICE              float64 `json:"sELLPRICE"              ` //
	SELLSECURITYID         string  `json:"sELLSECURITYID"         ` //
	SELLSETTLCURRFXRATE    string  `json:"sELLSETTLCURRFXRATE"    ` //
	SELLSETTLCURRENCY      string  `json:"sELLSETTLCURRENCY"      ` //
	SELLSETTLTYPE          string  `json:"sELLSETTLTYPE"          ` //
	SELLSTRIKEYEILDYILED   string  `json:"sELLSTRIKEYEILDYILED"   ` //
	SELLYTMYILED           float64 `json:"sELLYTMYILED"           ` //
	STATUS                 string  `json:"sTATUS"                 ` //
	SYMBOL                 string  `json:"sYMBOL"                 ` //
	TERMTOMATURITYSTRING   string  `json:"tERMTOMATURITYSTRING"   ` //
	TRANSACTTIME           string  `json:"tRANSACTTIME"           ` //
	USERREFERENCE1         string  `json:"uSERREFERENCE1"         ` //
	USERREFERENCE2         string  `json:"uSERREFERENCE2"         ` //
	USERREFERENCE3         string  `json:"uSERREFERENCE3"         ` //
	USERREFERENCE4         string  `json:"uSERREFERENCE4"         ` //
	USERREFERENCE5         string  `json:"uSERREFERENCE5"         ` //
	USERREFERENCE6         string  `json:"uSERREFERENCE6"         ` //
	VALIDUNTILTIME         string  `json:"vALIDUNTILTIME"         ` //
	QUOTESTATUSDESC        string  `json:"qUOTESTATUSDESC"        ` //
	BUYLASTQTY             float64 `json:"bUYLASTQTY"             ` //
	SELLLASTQTY            float64 `json:"sELLLASTQTY"            ` //
}
