// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CBMARKETQUOTESWDao is the data access object for table CBMARKETQUOTESW.
type CBMARKETQUOTESWDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns CBMARKETQUOTESWColumns // columns contains all the column names of Table for convenient usage.
}

// CBMARKETQUOTESWColumns defines and stores column names for table CBMARKETQUOTESW.
type CBMARKETQUOTESWColumns struct {
	ID               string //
	MDBOOKTYPE       string //
	MDENTRYDATE      string //
	MDENTRYPX        string //
	MDENTRYSIZE      string //
	MDENTRYTIME      string //
	MDENTRYTYPE      string //
	MDPRICELEVEL     string //
	MDQUOTETYPE      string //
	MDSUBBOOKTYPE    string //
	CLEARINGMETHOD   string //
	DELIVERYTYPE     string //
	LASTPX           string //
	MARKETDEPTH      string //
	MARKETINDICATOR  string //
	MATURITYYIELD    string //
	MDID             string //
	MDREQID          string //
	PARTYID101       string //
	PARTYID1018032   string //
	PARTYID101803266 string //
	QUOTEENTRYID     string //
	SECURITYID       string //
	SECURITYTYPE     string //
	SETTLCURRFXRATE  string //
	SETTLCURRENCY    string //
	SETTLDATE        string //
	SETTLTYPE        string //
	SYMBOL           string //
	INSERTTIME       string //
}

// cBMARKETQUOTESWColumns holds the columns for table CBMARKETQUOTESW.
var cBMARKETQUOTESWColumns = CBMARKETQUOTESWColumns{
	ID:               "ID",
	MDBOOKTYPE:       "MDBOOKTYPE",
	MDENTRYDATE:      "MDENTRYDATE",
	MDENTRYPX:        "MDENTRYPX",
	MDENTRYSIZE:      "MDENTRYSIZE",
	MDENTRYTIME:      "MDENTRYTIME",
	MDENTRYTYPE:      "MDENTRYTYPE",
	MDPRICELEVEL:     "MDPRICELEVEL",
	MDQUOTETYPE:      "MDQUOTETYPE",
	MDSUBBOOKTYPE:    "MDSUBBOOKTYPE",
	CLEARINGMETHOD:   "CLEARINGMETHOD",
	DELIVERYTYPE:     "DELIVERYTYPE",
	LASTPX:           "LASTPX",
	MARKETDEPTH:      "MARKETDEPTH",
	MARKETINDICATOR:  "MARKETINDICATOR",
	MATURITYYIELD:    "MATURITYYIELD",
	MDID:             "MDID",
	MDREQID:          "MDREQID",
	PARTYID101:       "PARTYID101",
	PARTYID1018032:   "PARTYID101_803_2",
	PARTYID101803266: "PARTYID101_803_266",
	QUOTEENTRYID:     "QUOTEENTRYID",
	SECURITYID:       "SECURITYID",
	SECURITYTYPE:     "SECURITYTYPE",
	SETTLCURRFXRATE:  "SETTLCURRFXRATE",
	SETTLCURRENCY:    "SETTLCURRENCY",
	SETTLDATE:        "SETTLDATE",
	SETTLTYPE:        "SETTLTYPE",
	SYMBOL:           "SYMBOL",
	INSERTTIME:       "INSERTTIME",
}

// NewCBMARKETQUOTESWDao creates and returns a new DAO object for table data access.
func NewCBMARKETQUOTESWDao() *CBMARKETQUOTESWDao {
	return &CBMARKETQUOTESWDao{
		group:   "default",
		table:   "CBMARKETQUOTESW",
		columns: cBMARKETQUOTESWColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CBMARKETQUOTESWDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CBMARKETQUOTESWDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CBMARKETQUOTESWDao) Columns() CBMARKETQUOTESWColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CBMARKETQUOTESWDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CBMARKETQUOTESWDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CBMARKETQUOTESWDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
