// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MMQUOTESET is the golang structure for table MM_QUOTE_SET.
type MMQUOTESET struct {
	BONDCODE       string  `json:"BONDCODE"       ` //
	BASEYIELD      float64 `json:"BASEYIELD"      ` //
	MIDYIELDADD    float64 `json:"MIDYIELDADD"    ` //
	MIDYIELDSUB    float64 `json:"MIDYIELDSUB"    ` //
	BESTYIELDADD   float64 `json:"BESTYIELDADD"   ` //
	BESTYIELDSUB   float64 `json:"BESTYIELDSUB"   ` //
	BESTYIELDTYPE  int     `json:"BESTYIELDTYPE"  ` //
	SETYIELDBUY    float64 `json:"SETYIELDBUY"    ` //
	SETYIELDSELL   float64 `json:"SETYIELDSELL"   ` //
	BESTBID        float64 `json:"BESTBID"        ` //
	SECONDBID      float64 `json:"SECONDBID"      ` //
	BESTOFR        float64 `json:"BESTOFR"        ` //
	SECONDOFR      float64 `json:"SECONDOFR"      ` //
	SELFBID        float64 `json:"SELFBID"        ` //
	SELFOFR        float64 `json:"SELFOFR"        ` //
	BESTMIDYIELD   float64 `json:"BESTMIDYIELD"   ` //
	SECONDMIDYIELD float64 `json:"SECONDMIDYIELD" ` //
	SETTLETYPE     int     `json:"SETTLETYPE"     ` //
	BUYQTY         int     `json:"BUYQTY"         ` //
	SELLQTY        int     `json:"SELLQTY"        ` //
	MAXFLOOR       int     `json:"MAXFLOOR"       ` //
	CANSEND        int     `json:"CANSEND"        ` //
}
