// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NewMarkerMaker/internal/dao/internal"
)

// internalCBMARKETQUOTESWDao is internal type for wrapping internal DAO implements.
type internalCBMARKETQUOTESWDao = *internal.CBMARKETQUOTESWDao

// cBMARKETQUOTESWDao is the data access object for table CBMARKETQUOTESW.
// You can define custom methods on it to extend its functionality as you wish.
type cBMARKETQUOTESWDao struct {
	internalCBMARKETQUOTESWDao
}

var (
	// CBMARKETQUOTESW is globally public accessible object for table CBMARKETQUOTESW operations.
	CBMARKETQUOTESW = cBMARKETQUOTESWDao{
		internal.NewCBMARKETQUOTESWDao(),
	}
)

// Fill with you ideas below.
