// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NewMarkerMaker/internal/dao/internal"
)

// internalCBMARKETQUOTEDao is internal type for wrapping internal DAO implements.
type internalCBMARKETQUOTEDao = *internal.CBMARKETQUOTEDao

// cBMARKETQUOTEDao is the data access object for table CBMARKETQUOTE.
// You can define custom methods on it to extend its functionality as you wish.
type cBMARKETQUOTEDao struct {
	internalCBMARKETQUOTEDao
}

var (
	// CBMARKETQUOTE is globally public accessible object for table CBMARKETQUOTE operations.
	CBMARKETQUOTE = cBMARKETQUOTEDao{
		internal.NewCBMARKETQUOTEDao(),
	}
)

// Fill with you ideas below.
